[package]
name = "jsonedit"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
serde = "1.0.217"
serde_json = { version = "1.0.134", features = ["preserve_order"] }
serde_json_path = "0.7.1"
