from_latest_tag = false
ignore_merge_commits = false
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
branch_whitelist = []
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = []
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []
tag_prefix = "v"

[git_hooks]

[commit_types]
chore = { changelog_title = "Misc.", omit_from_changelog = false }

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "jsonedit"
owner = "oatmealdealer"
authors = [
    { username = "oatmealdealer", signature = "Julian Giamblanco" }
]

[bump_profiles]

[packages]
